# Generated by Django 4.1.2 on 2022-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='careers',
            new_name='career',
        ),
    ]
