# Generated by Django 4.1.2 on 2022-10-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_careers_class_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='career',
        ),
        migrations.AddField(
            model_name='career',
            name='_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.class'),
            preserve_default=False,
        ),
    ]
