# Generated by Django 4.1.2 on 2022-10-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_class_career_career__class'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='careers',
            field=models.ManyToManyField(to='main.career'),
        ),
    ]
