# Generated by Django 4.1.2 on 2022-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_careers_species_disallowed_careers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('characteristic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_advanced', models.BooleanField(default=False)),
                ('is_grouped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tests', models.CharField(max_length=255)),
                ('bonus_when_maxed', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.ManyToManyField(to='main.skill'),
        ),
        migrations.AddField(
            model_name='career',
            name='talents',
            field=models.ManyToManyField(to='main.talent'),
        ),
        migrations.AddField(
            model_name='species',
            name='skills',
            field=models.ManyToManyField(to='main.skill'),
        ),
        migrations.AddField(
            model_name='species',
            name='talents',
            field=models.ManyToManyField(to='main.talent'),
        ),
    ]
