# Generated by Django 4.1.2 on 2022-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_career_author_class_author_game_author_skill_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.CharField(default='aaaaaaaaaaaaaa', max_length=64),
            preserve_default=False,
        ),
    ]
