# Generated by Django 4.1.2 on 2022-10-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_game_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='short_description',
            field=models.CharField(default='short description', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='short_description',
            field=models.CharField(default='short description', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='short_description',
            field=models.CharField(default='short description', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='short_description',
            field=models.CharField(default='short description', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talent',
            name='short_description',
            field=models.CharField(default='short description', max_length=64),
            preserve_default=False,
        ),
    ]
