# Generated by Django 4.1.2 on 2022-10-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename__class_career_class_for_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='short_description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='class',
            name='short_description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='skill',
            name='short_description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='species',
            name='short_description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='talent',
            name='short_description',
            field=models.CharField(max_length=128),
        ),
    ]
