# Generated by Django 4.1.2 on 2022-10-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_career_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='tests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
